name: Generate Documentation

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install pdoc3

      - name: Generate documentation
        run: |
          # Create a temporary directory for documentation
          mkdir -p temp_docs
          
          # Generate documentation in the temporary directory
          pdoc --html --output-dir temp_docs datacuration_api datacuration_cli
          
          # Create the final docs directory
          mkdir -p docs
          
          # Copy the generated documentation to the docs directory
          cp -r temp_docs/datacuration_api/* docs/
          cp -r temp_docs/datacuration_cli/* docs/
          
          # Ensure the custom documentation files are preserved
          # (They're already in the docs directory from the checkout)
          
          # Add .nojekyll file to disable Jekyll processing
          touch docs/.nojekyll
          
          # Create an index.html file that redirects to client.html
          echo '<html><head><meta http-equiv="refresh" content="0;URL=client.html"></head></html>' > docs/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
